[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  [context.production.environment]
    HUGO_VERSION = "0.25"

[context.deploy-preview]
  command = "npm run build-preview"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.25"
